server:
  port: 8080

spring:
  profiles:
    active: dev
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    #password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin


---

spring:
     profiles: dev
logging:
  level:
    com.zxh: debug
