server:
  port: 8082

spring:
  application:
    name: crawler-persistent
  profiles:
    active: dev
  cloud:
    inetutils:
      ignored-interfaces:
        - docker 0

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin



## Dubbo 服务提供者配置
dubbo:
  application:
    name: crawler-persistent
    #-- 注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181
    #-- dubbo 协议
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.zxh.crawlerpersistent.service.proxy




mybatis:
  type-aliases-package: com.zxh.crawlerpersistent.model
  mapper-locations: classpath:mapping/*.xml

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/crawler?serverTimezone=UTC
    data-username: root
    data-password: root
    #driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        url-pattern: "/druid/*"
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
logging:
  level:
    com.zxh: debug